### PR TITLE
[CMake] Bump project version 0.2.0 -> 0.5.0

### LINKED ISSUE #536: [CMake] Project version does not match release tag
# Summary

The lastest source release of this project is tagged v0.4 (https://github.com/oneapi-src/oneMKL/releases/tag/v0.4). The CMake gives the version as 0.2 (see https://github.com/oneapi-src/oneMKL/blob/8abfdfcbb9fe7fe2e6eea1214478f62e30e4db18/CMakeLists.txt#L188). The version reported by the CMake and the version should probably match the version given in the tags.

# Expected Behavior

* The CMake of the tagged releases should match the version given in the tag.
* Q: What version should the develop branch have?

### PR DESCRIPTION
**Pull request by hjabird**
# Description

* Bump version given in CMake to match the next version to be released.

Fixes https://github.com/oneapi-src/oneMKL/issues/536

# Checklist

## All Submissions

- [N/A] Do all unit tests pass locally? Attach a log.
- [N/A] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by hjabird** [comment]
It is not clear to me what the version should be inbetween releases. I've chosen 0.5.0 since it means no further PRs are needed for the next source release.

**Review by Rbiessy — APPROVED** [review]

**Comment by Rbiessy** [comment]
Pinging @toxicscum since he is taking care of the releases.

**Comment by toxicscum** [comment]
Hi, we plan to update version 0.4 -> 0.5 in two weeks. Can we update this PR with 0.4 so far or postpone its merge till the version bump?

**Comment by hjabird** [comment]
> Can we update this PR with 0.4 so far or postpone its merge till the version bump?

It is probably easiest to prospone merging this for a bit. I'm not aware of anyone depending on the correct value of this at the moment.

**Comment by dnhsieh-intel** [comment]
We actually have another place about version
https://github.com/oneapi-src/oneMKL/blob/b4955cae8240c8ca6b088160abaadb7fd0a245b3/docs/conf.py.in#L29
The version is visible in the old documentation theme, but I didn't find the version appearing in the current documentation.

**Comment by toxicscum** [comment]
Hi @hjabird,
v0.5 published. Could you merge this now?

**Comment by hjabird** [comment]
It needs a second approval first!

**Review by mkrainiuk — APPROVED** [review]

**Pull request merged**
