### PR TITLE
Updated BLAS domain with exact copy-over from oneMKL spec per SME dir…

### PR DESCRIPTION
**Pull request by JOCwriter**
…ection.

Added exceptions.inc.rst to oneMKL/docs to resolve cross references used in BLAS topics, and added exceptions.inc.rst to the index toctree.

Signed-off-by: John O'Connell <john.oconnell@intel.com>

# Description

Please include a summary of the change. Please also include relevant
motivation and context. See
[contribution guidelines](https://github.com/oneapi-src/oneMKL/blob/master/CONTRIBUTING.md)
for more details. If the change fixes an issue not documented in the project's
Github issue tracker, please document all steps necessary to reproduce it.

Fixes # (GitHub issue)

# Checklist

## All Submissions

- [ ] Do all unit tests pass locally? Attach a log.
- [ ] Have you formatted the code using clang-format?

## New interfaces

- [ ] Have you provided motivation for adding a new feature as part of RFC and
it was accepted? # (RFC)
- [ ] What version of oneAPI spec the interface is targeted?
- [ ] Complete [New features](pull_request_template.md#new-features) checklist

## New features

- [ ] Have you provided motivation for adding a new feature?
- [ ] Have you added relevant tests?

## Bug fixes

- [ ] Have you added relevant regression tests?
- [ ] Have you included information on how to reproduce the issue (either in a
      GitHub issue or in this PR)?

### CODE REVIEW

**Comment by JOCwriter** [comment]
@mkrainiuk / @mmeterel , Please review. Per our agreement, I have updated BLAS domain with everything from existing spec.

**Comment by JOCwriter** [comment]
@mmeterel / @mkrainiuk , gentle nudge. This PR needs to be assigned, but I don' thave the option to set reviewers. Please review.

**Comment by mmeterel** [comment]
@JOCwriter My main comment about this PR is the exception handling in the oneMKL open source interfaces - which is different than how it is described in the new documentation. @mkrainiuk do you have any feedback/recommendation on how to handle the exceptions section in the new documentation?

**Comment by JOCwriter** [comment]
@mkrainiuk / @mmeterel 
Thank you Mesut for the review. Please suggest the specific changes that need to be made to comply with open source implementations strategy. I'm trying to get this wrapped up by 2021.4. In our last meeting, my understanding was that all of the spec (with respect to BLAS) could be copied over and used. It turns out that there are several references in the BLAS topics to this exceptions topic, which I understood to be also valid.

**Comment by mmeterel** [comment]
@JOCwriter Regarding BLAS documentation, all the spec could be re-used in terms of API descriptions. This will be much faster than updating the documentation here manually, based on personal experience. Exceptions in the spec describe what needs to be happen in the implementation, however, oneMKL open source interfaces did not implement it yet. I believe, the documentation in this repo should reflect what is supported here, not in the spec or in the Intel oneMKL product. Mixing documentation will lead to confusion. That is why I want Maria's feedback on exceptions.

One option would be to remove all references to exceptions in API pages. (Again, even this will be much faster than updating the documents manually here)

How about other domains like RNG and LAPACK? Will you be adding those docs as well?

**Comment by JOCwriter** [comment]
@mmeterel ,

Unfortunately, RNG and LAPACK fell out of scope for the 2021.4 deadline due to the misalignment between the initial strategy and the additional input we received from the team. We will bring those domains into scope for phase 2 (2022.1), however. Please let me know at your earliest what you and @mkrainiuk agree is the best path forward for the BLAS exception handling approach.

**Comment by mmeterel** [comment]
There were some recent additions/changes to oneAPI spec for BLAS domain. We will open another PR to bring oneAPI spec with recent changes. Closing this PR.

**Pull request closed without merging**
