### PR TITLE
[BLAS] Add missing copyright banner

### PR DESCRIPTION
**Pull request by mmeterel**
# Description

Add missing copyright banner for 1 file.

## All Submissions

- [ ] Do all unit tests pass locally? N/A
- [X] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by andrewtbarker** [comment]
Looks fine to me.

**Review by andrewtbarker — APPROVED** [review]

**Review by dnhsieh-intel — COMMENTED** [review]
This file was created by sbalint98. Should the copyright be Heidelberg University? For example:
https://github.com/oneapi-src/oneMKL/blob/33a0bde43ae0cd875620c30e673df317bc27f63b/CMakeLists.txt#L3

**Comment by mmeterel** [comment]
> This file was created by sbalint98. Should the copyright be Heidelberg University? For example:
> 
> https://github.com/oneapi-src/oneMKL/blob/33a0bde43ae0cd875620c30e673df317bc27f63b/CMakeLists.txt#L3

I was matching the copyright banners with the files in the same folder. But either is fine with me. We can add that line if you prefer.

**Comment by dnhsieh-intel** [comment]
@sbalint98 Thank you for creating and contributing the file [cublas_task.hpp](https://github.com/oneapi-src/oneMKL/blob/develop/src/blas/backends/cublas/cublas_task.hpp)! Could you please let us know what you like to have as copyright for this file?

**Comment by mmeterel** [comment]
@dnhsieh-intel I added the Heidelberg University copyright banner as well.

**Comment by dnhsieh-intel** [comment]
@mmeterel Thank you! I am OK with it.
@sbalint98 We will merge it as it is now. Please let us know if you want to make changes later.

**Review by dnhsieh-intel — APPROVED** [review]

**Pull request merged**
