### PR TITLE
[LAPACK][DOCS] Add LAPACK documentation

### PR DESCRIPTION
**Pull request by ericlars**
# Description
Include LAPACK documentation from oneAPI spec.

### CODE REVIEW

**Comment by ericlars** [comment]
Noting that when building docs, at least some backend must also be selected for building.

**Review by jadurazo — APPROVED** [review]
Looks good!

**Review by mkrainiuk — APPROVED** [review]

**Comment by mkrainiuk** [comment]
Thanks @ericlars! 
@trosenqu do you know if we need to re-build documentation to enable LAPACK part in online documentation?

**Comment by trosenqu** [comment]
> @trosenqu do you know if we need to re-build documentation to enable LAPACK part in online documentation?

Yes, we'll need to re-build with this new content. Until CI is in place, infodev can build and publish.

**Comment by mmeterel** [comment]
@ericlars I am not sure if the exceptions in the API pages apply to this repo. Can we consider removing them?

**Review by sknepper — APPROVED** [review]
These look good - thanks!

**Comment by ericlars** [comment]
@mmeterel Thanks, I will remove

**Pull request merged**
