### PR TITLE
Add namespace for BLAS domain

### LINKED ISSUE #59: Improper namespace for BLAS domain
# Summary
Namespace scopes in oneAPI are of the form `oneapi::mkl::domain`, e.g. `oneapi::mkl::blas` and `oneapi::mkl::rng`. In oneMKL, the RNG domain libraries are of the form `oneapi::mkl::rng::library`, e.g. `oneapi::mkl::rng::mklgpu`.

# Problem statement
The namespace convention in oneMKL differs between the BLAS and RNG domain libraries; where BLAS uses `oneapi::mkl::library` for library namespaces, RNG uses -- more appropriately -- `oneapi::mkl::rng::library`. This observation was made when reading through [Integrating a Third-party Library to oneAPI Math Kernel Library (oneMKL) Interfaces](https://github.com/oneapi-src/oneMKL/blob/master/docs/create_new_backend.rst):
```
python scripts/generate_backend_api.py include/oneapi/mkl/blas.hpp \                                  # Base header file
                                       include/oneapi/mkl/blas/detail/newlib/onemkl_blas_newlib.hpp \ # Output header file
                                       oneapi::mkl::newlib                                            # Wrappers namespace
```
where I believe it should be:
```
python scripts/generate_backend_api.py include/oneapi/mkl/blas.hpp \                                  # Base header file
                                       include/oneapi/mkl/blas/detail/newlib/onemkl_blas_newlib.hpp \ # Output header file
                                       oneapi::mkl::domain::newlib                                    # Wrappers namespace
```
With the former instruction, adding a new third-party library to the RNG domain generates an incorrect namespace, e.g. `
onemkl_rng_curand.hpp`:
```
...
namespace oneapi {
namespace mkl {
namespace curand {} // namespace curand
} // namespace mkl
} // namespace oneapi
```
while it should be:
```
...
namespace oneapi {
namespace mkl {
namespace rng {
namespace curand {} // namespace curand
} // namespace rng
} // namespace mkl
} // namespace oneapi
```

# Preferred solution
The BLAS domain should be namespace'd consistently with the RNG domain. That is, more suitable would be:
```
oneapi::mkl::mklcpu --> oneapi::mkl::blas::mklcpu
oneapi::mkl::mklgpu --> oneapi::mkl::blas::mklgpu
oneapi::mkl::netlib --> oneapi::mkl::blas::netlib
oneapi::mkl::cublas --> oneapi::mkl::blas::cublas
```
which matches the RNG domain:
```
oneapi::mkl::rng::mklcpu
oneapi::mkl::rng::mklgpu
```
This also better reflects the header file naming convention, e.g. `onemkl_blas_netlib.hpp`.

If this is an acceptable change, I will make a new PR.

### PR DESCRIPTION
**Pull request by vrpascuzzi**
# Description

The BLAS domain should be namespace'd consistently with the RNG domain. This commit adds a `blas` namespace to the BLAS domain.

Fixes #59

# Checklist

## All Submissions

- [ ] Do all unit tests pass locally?
  All except iGPU (see comment [here](https://github.com/oneapi-src/oneMKL/pull/62#issuecomment-747139378)).
[ctest_onemkl_cublas.LOG](https://github.com/oneapi-src/oneMKL/files/5710665/ctest_onemkl_cublas.LOG)
[ctest_onemkl_mklcpu_mklgpu.LOG](https://github.com/oneapi-src/oneMKL/files/5710667/ctest_onemkl_mklcpu_mklgpu.LOG)
[ctest_onemkl_netlib.LOG](https://github.com/oneapi-src/oneMKL/files/5710668/ctest_onemkl_netlib.LOG)
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by mmeterel** [comment]
Hi @vrpascuzzi, please let us know when this PR is ready for review.

**Comment by vrpascuzzi** [comment]
For sure! Sorry, working from home since Monday (Dec. 8) and internet connection has been dropping constantly...

**Comment by vrpascuzzi** [comment]
Back online. Getting to this now.

**Comment by mmeterel** [comment]
Sure. I am on vacation, but I should be able to test/review the PR. :)

**Comment by vrpascuzzi** [comment]
@mmeterel,
I hope your vacation has so far been nice! 

For tests, do we include the results from the `ctest` or by running the individual tests in `bin`, e.g. `test_main_blas_rt?

**Comment by vmalia** [comment]
> @mmeterel,
> I hope your vacation has so far been nice!
> 
> For tests, do we include the results from the `ctest` or by running the individual tests in `bin`, e.g. `test_main_blas_rt`?

You can run a full ctest command with "-O <file>, --output-log <file>" option and upload that log. We should test both Compile-time and Run-time dispatching. It is okay to run only BLAS tests, unless you change anything in a file used by RNG as well. You can skip RNG tests for a cleaner log.

Hope that helps.

**Comment by vrpascuzzi** [comment]
@vmalia,

Yes, that's helpful -- thanks.

One problem: there seems to be an issue with my Gen9 driver setup/install. All tests end in a segfault when running `ctest`, although running the binaries directly shows tests "OK". The segfaults appear unrelated to my changes as I get the same behavior when running the tests from `master`. It's odd because I've used the iGPU before successfully (albeit not with BLAS tests) and it's shown as a CL device via `clinfo`. The tests for the CPU device are fine:
```
<...>
100% tests passed, 0 tests failed out of 1408

Total Test time (real) = 441.56 sec
```

Maybe I'm missing something -- can you give me an exact command to run?

**Comment by vmalia** [comment]
Good catch - we found these test failures and segfaults too. In the binary oneMKL product, we load the Level0 driver, but it gets unloaded before we unload it explicitly. Hence, the segfault. This appears to be a compiler bug, which was submitted today. We can ignore those segfaults for this PR.

**Comment by vrpascuzzi** [comment]
Ah, man -- I've spent a good chunk of time trying to debug this! Anyways, thanks for the peace-of-mind.

I can sleep tonight.

**Comment by vmalia** [comment]
> Ah, man -- I've spent a good chunk of time trying to debug this! Anyways, thanks for the peace-of-mind.
> 
> I can sleep tonight.

Sorry for the inconvenience @vrpascuzzi We will try to mention know issues from next time onwards more proactively, to avoid wasting developer time. Thank you for your help.

**Comment by vrpascuzzi** [comment]
I think this one is good to go.

**Review by vmalia — APPROVED** [review]
Looks good to me. Let's wait for Mesut's review too.

**Comment by vmalia** [comment]
Hi @mmeterel I just want to clarify that we do need to run a CI before we can approve these changes. I forgot to do that, but it is not too late. The infrastructure is down today for some maintenance, but once it is up, We can start a CI using the comment-hooks.

No action is required from @vrpascuzzi at the moment.

**Comment by mmeterel** [comment]
@vmalia Thanks for running the CI. Windows GEN9 tests are ongoing as I write this. I saw that Linux(Ubuntu) GEN9 test with DPC++ compiler can not find any devices. I remember, I fixed this before. This might be due to this [PR](https://github.com/oneapi-src/oneMKL/pull/66). Could you please take a look? This issue is not related to this PR. Other tests look good. 

Once the windows tests come back clean, this PR will be approved. @vrpascuzzi Thanks for your efforts!

**Review by mmeterel — APPROVED** [review]

**Comment by mmeterel** [comment]
@vrpascuzzi , Thanks again for the PR. It is merged now. Please continue with your valuable contributions.

**Pull request merged**
