### PR TITLE
Add option to enable tests on OpenCL devices

### PR DESCRIPTION
**Pull request by Rbiessy**
We are working on adding support for a wider range of devices. In that context it makes sense to allow testing on more devices.

# Description

Please include a summary of the change. Please also include relevant
motivation and context. See
[contribution guidelines](https://github.com/oneapi-src/oneMKL/blob/master/CONTRIBUTING.md)
for more details. If the change fixes an issue not documented in the project's
Github issue tracker, please document all steps necessary to reproduce it.

Fixes # (GitHub issue)

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Attach a log.
- [x] Have you formatted the code using clang-format?

## New interfaces

- [ ] Have you provided motivation for adding a new feature as part of RFC and
it was accepted? # (RFC)
- [ ] What version of oneAPI spec the interface is targeted?
- [ ] Complete [New features](pull_request_template.md#new-features) checklist

## New features

- [ ] Have you provided motivation for adding a new feature?
- [ ] Have you added relevant tests?

## Bug fixes

- [ ] Have you added relevant regression tests?
- [ ] Have you included information on how to reproduce the issue (either in a
      GitHub issue or in this PR)?

### CODE REVIEW

**Comment by Rbiessy** [comment]
Log running the tests on OpenCL devices: [log_onemkl_opencl_cpu_gpu.txt](https://github.com/oneapi-src/oneMKL/files/10796647/log_onemkl_opencl_cpu_gpu.txt)
I am using `-DENABLE_OPENCL_TESTS=ON` and my devices are:
```
$ sycl-ls
[opencl:acc:0] Intel® FPGA Emulation Platform for OpenCL™, Intel® FPGA Emulation Device 1.2 [2022.15.12.0.01_081451]
[opencl:cpu:1] Intel® OpenCL, Intel® Core™ i7-6700K CPU @ 4.00GHz 3.0 [2022.15.12.0.01_081451]
[opencl:gpu:2] Intel® OpenCL HD Graphics, Intel® HD Graphics 530 [0x1912] 3.0 [22.08.22549]
```

I could not get the lapack tests passing using the Level Zero drivers so I'm not sure the failures seen here are relevant.

This change is useful for our testing with https://github.com/oneapi-src/oneMKL/pull/262 and https://github.com/oneapi-src/oneMKL/pull/259

**Comment by mmeterel** [comment]
@Rbiessy Could you please add more clarification/motivation for this change? What specific devices are you talking about? The default backend for oneAPI is level_zero, hence we should be promoting level_zero usage. There are also discussions about dropping opencl backend support from oneMKL product, so, this PR kind of conflicts with that.

**Comment by Rbiessy** [comment]
@mmeterel I was thinking of devices we support in SYCL-BLAS or other Codeplay projects like R-Car, PowerVR or Mali GPUs.
I'll close this MR if we should focus on level_zero instead.

**Comment by mmeterel** [comment]
> @mmeterel I was thinking of devices we support in SYCL-BLAS or other Codeplay projects like R-Car, PowerVR or Mali GPUs. I'll close this MR if we should focus on level_zero instead.

Yes, I think level_zero should be our main focus, unless there is a strong request from users.

**Pull request closed without merging**
