### PR TITLE
Add Nvidia lapack support (cusolver backend)

### PR DESCRIPTION
**Pull request by AidanBeltonS**
# Description
This PR introduces the cusolver backend. This is to provide Nvidia GPU support for lapack functions.
The backend is based on the existing cublas backend. The behaviour of the cusolver scope handle is identical to the cublas scope handle.
This has been tested with an implementation of the potrf batch, usm, and scratchpad functions.
Additional maths functions will be added in follow up PRs.
The cusolver legacy 32-bit API is used for the implementation as it has more maths operations then the new 64-bit cusolver API.

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Attach a [log.]
- [x] Have you formatted the code using clang-format?

Test Results:
[test_main_lapack_ct_results.txt](https://github.com/oneapi-src/oneMKL/files/7821060/test_main_lapack_ct_results.txt)
[test_main_lapack_rt_results.txt](https://github.com/oneapi-src/oneMKL/files/7821062/test_main_lapack_rt_results.txt)

### CODE REVIEW

**Comment by AidanBeltonS** [comment]
Added gebrd, geqrf, getrf, getrs, and gesvd buffer and USM function implementations.

Details:
* getrs_scratchpad_size returns 0 as the cusolver function does not use any scratchpad memory.
* getrf and getrs have `ipiv` memory array of 64-bit ints. cusolver legacy API does not support 64-bit ints. So ipiv is changed to 32 bits using a SYCL kernel.
* gebrd does not support m<n and throws unimplemented exception if matrix dimensions satisfy this constraint

Attached test results:
[ct_results.txt](https://github.com/oneapi-src/oneMKL/files/7838748/ct_results.txt)
[rt_results.txt](https://github.com/oneapi-src/oneMKL/files/7838749/rt_results.txt)

**Comment by AidanBeltonS** [comment]
@ericlars would it be possible to see the results of the check, so I can look into what is failing?

**Comment by AidanBeltonS** [comment]
I think that all non-batch cusolver functions, which match oneMKL functions, have been added.
The full list of implemented operations is, gebrd, geqrf, getrf, getrs, gesvd, orgbr, orgqr, orgtr, ormtr, ormqr, potrf, potri, potrs, syevd, sytrd, sytrf, heevd, hegvd, hetrd, sygvd, ungbr, ungqr, ungtr, unmqr, and unmtr.

cc, @pgorlani, @hdelan

Test results are below:
[test_main_lapack_ct_results.txt](https://github.com/oneapi-src/oneMKL/files/7907132/test_main_lapack_ct_results.txt)
[test_main_lapack_rt_results.txt](https://github.com/oneapi-src/oneMKL/files/7907133/test_main_lapack_rt_results.txt)

**Comment by ericlars** [comment]
> @ericlars would it be possible to see the results of the check, so I can look into what is failing?

All tests passed on gpu! There are a couple failures on CPU when LLVM is used, and lots of failures outside of LAPACK domain, but they all look unrelated to this PR. I'm looking into why that is.

Thanks for the PR, it looks great!

**Review by rachelertl — APPROVED** [review]

**Review by ericlars — APPROVED** [review]

**Review by sknepper — APPROVED** [review]

**Comment by mmeterel** [comment]
@ericlars  Is this backend already added into CI?

**Pull request merged**
