### PR TITLE
Jocwriter/asum dotu

### PR DESCRIPTION
**Pull request by JOCwriter**
# Description

Please include a summary of the change. Please also include relevant
motivation and context. See
[contribution guidelines](https://github.com/oneapi-src/oneMKL/blob/master/CONTRIBUTING.md)
for more details. If the change fixes an issue not documented in the project's
Github issue tracker, please document all steps necessary to reproduce it.

Fixes # (GitHub issue)

# Checklist

## All Submissions

- [ ] Do all unit tests pass locally? Attach a log.
- [ ] Have you formatted the code using clang-format?

## New interfaces

- [ ] Have you provided motivation for adding a new feature as part of RFC and
it was accepted? # (RFC)
- [ ] What version of oneAPI spec the interface is targeted?
- [ ] Complete [New features](pull_request_template.md#new-features) checklist

## New features

- [ ] Have you provided motivation for adding a new feature?
- [ ] Have you added relevant tests?

## Bug fixes

- [ ] Have you added relevant regression tests?
- [ ] Have you included information on how to reproduce the issue (either in a
      GitHub issue or in this PR)?

### CODE REVIEW

**Comment by JOCwriter** [comment]
@mkrainiuk/ @mmeterel  , This is the first of many similar PRs to come. I notice that I am unable to assign reviewers/approvers when I open a PR. Is that intentional? Do I need to @ mention you in the comment field every time? Just trying to learn how to interact with this repo. :-)

Best regards,
John

**Comment by mmeterel** [comment]
> @mkrainiuk/ @mmeterel , This is the first of many similar PRs to come. I notice that I am unable to assign reviewers/approvers when I open a PR. Is that intentional? Do I need to @ mention you in the comment field every time? Just trying to learn how to interact with this repo. :-)
> 
> Best regards,
> John

@JOCwriter are you planning to send a PR for each API? :) IMHO, it would be easier to review all at once so that we can check the consistency between APIs. 

Also, what I was doing for this documentation is: I was first updating the oneAPI spec and then copying the files over this repository. Why aren't we doing something similar? Basically keep the oneAPI spec latest and golden, and then copy them over here. I would even suggest we can remove the documentation here and refer to the oneAPI spec so that we have a single copy to maintain. I think we need to have a discussion on how to manage these repositories before we start modifying.

**Comment by JOCwriter** [comment]
Hi @mmeterel , I was making changes in batches of approximately 10-15 apis at a time to keep the PRs relatively small. I'm not making any changes to the technical content, just applying templates. 

It is helpful to know what your process was. When I see things like this: `.. rubric:: Description` in the docs, this is unnecessary clutter that is a result of a scripted conversion. I'm also seeing a lot of indented tables which I am fixing. Let's have a meeting and please invite Anastasiya Ageeva, because she is coordinating the libraries open source documentation alignment initiative. She may have some insights about your proposal to simply point to the spec documentation. My target for these fixes is 2021.4, so let's discuss it soon. In the meantime, I will continue the cleanup effort.

Best regards,
John

**Comment by mmeterel** [comment]
> Hi @mmeterel , I was making changes in batches of approximately 10-15 apis at a time to keep the PRs relatively small. I'm not making any changes to the technical content, just applying templates.
> 
> It is helpful to know what your process was. When I see things like this: `.. rubric:: Description` in the docs, this is unnecessary clutter that is a result of a scripted conversion. I'm also seeing a lot of indented tables which I am fixing. Let's have a meeting and please invite Anastasiya Ageeva, because she is coordinating the libraries open source documentation alignment initiative. She may have some insights about your proposal to simply point to the spec documentation. My target for these fixes is 2021.4, so let's discuss it soon. In the meantime, I will continue the cleanup effort.
> 
> Best regards,
> John

@JOCwriter I actually forgot to mention in my earlier reply. I spent a lot of time to update all the BLAS APIs according an accepted (accepted by oneMKL team in spec work group) template and merged them to oneAPI spec repository. They are also in sync with other domains. So, the documents here are very very old and I would not suggest starting from these ones. Could you please take a look at the oneAPI spec documentation and see if they look good? In my opinion, any change in BLAS documentation needs to be applied to other domains as well to be consistent. 
I am on vacation next week between Tue and Friday. Please feel free to schedule a meeting on Monday.

**Comment by JOCwriter** [comment]
The team preferred to preserve the non-templatized content from the spec, so this PR is unnecessary; hence, closing.

**Pull request closed without merging**
