### PR TITLE
[RNG] Refactored the curand backend

### PR DESCRIPTION
**Pull request by andreyfe1**
Refactoring includes following:
* SYCL 2020 API changes.
* Removing unnecessary wait calls for SYCL buffer and USM API both.

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? [log.txt](https://github.com/oneapi-src/oneMKL/files/13659464/log.txt)
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Review by aelizaro — APPROVED** [review]
Changes looks great to me, thank you @andreyfe1!

**Review by egrabovskaya — APPROVED** [review]

**Comment by JackAKirk** [comment]
Hi @andreyfe1 

I just have a question about the removal of the `wait_and_throw`s in this PR, In particular I was wondering if there was a reason that you left in the wait_and_throw for the `oneapi::mkl::rng::uniform_method::standard` generate function?

According to curand docs these funcs are asyncronous: see https://docs.nvidia.com/cuda/curand/host-api-overview.html#host-api-example

relevant excerpt:

"Note that curandGenerate() in step 4 above launches a kernel and returns asynchronously. If you launch another kernel in a different stream, and that kernel needs to use the results of curandGenerate(), you must either call cudaThreadSynchronize() or use the stream management/event management routines, to ensure that the random generation kernel has finished execution before the new kernel is launched. "

However we know that actually some cusolver calls that are meant to be asyncronous actually aren't. I'm just curious whether you tested this and found something similar?

Otherwise I may add back stream synchronization to support the standard host_task 2020 case that does not wait for asyncronous native calls.

Thanks.

**Comment by andreyfe1** [comment]
Hi @JackAKirk,
The reason for removal was that `wait_and_throw()` was an extra synchronization. For users it's an extra call during profiling.

>if there was a reason that you left in the wait_and_throw for the `oneapi::mkl::rng::uniform_method::standard` generate function?

Do you mean [this call](https://github.com/oneapi-src/oneMKL/blob/develop/src/rng/backends/curand/mrg32k3a.cpp#L346)? This is because we need to allocate a [temporary memory](https://github.com/oneapi-src/oneMKL/blob/develop/src/rng/backends/curand/mrg32k3a.cpp#L335) and we need to synchronize until we release the memory to not have the dangling reference. Unfortunately this call is synchronous.

**Comment by JackAKirk** [comment]
> Hi @JackAKirk, The reason for removal was that `wait_and_throw()` was an extra synchronization. For users it's an extra call during profiling.
> 
> > if there was a reason that you left in the wait_and_throw for the `oneapi::mkl::rng::uniform_method::standard` generate function?
> 
> Do you mean [this call](https://github.com/oneapi-src/oneMKL/blob/develop/src/rng/backends/curand/mrg32k3a.cpp#L346)? This is because we need to allocate a [temporary memory](https://github.com/oneapi-src/oneMKL/blob/develop/src/rng/backends/curand/mrg32k3a.cpp#L335) and we need to synchronize until we release the memory to not have the dangling reference. Unfortunately this call is synchronous.

Yeah, thanks for the info!

**Pull request merged**
