### PR TITLE
[cublas] Fix build for CUDA 11.x

### PR DESCRIPTION
**Pull request by npmiller**
# Description

In CUDA 11 the type of one of the argument of `cublasGemmEx` has been
changed, but CUDA does provide an overload with the previous argument
type for backwards compatibility.

However because it is used as a template argument the introduction of
that overload seemingly broke the template resolution.

This patch simply removes that function from the template arguments and
calls it directly in the intermediary templated function.

This still uses the old signature for `cublasGemmEx` so should work fine
for CUDA 10.x and relies on the compatibility overload for CUDA 11.x.

With this patch oneMKL builds successfully with CUDA 11.4.

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Attach a log.
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by mmeterel** [comment]
@npmiller Thanks for the PR. A few questions for clarity:

1. Why do we need to switch to CUDA 11.x? 
2. Has this change (CUDA version change) propagated to README? I did not see it in #126 
3. Did you attach the log? I could not find it. 
4. @mkrainiuk, @jasukhar If we are changing the supported CUDA version, I think, we need to update our CI system as well.

**Comment by npmiller** [comment]
> @npmiller Thanks for the PR. A few questions for clarity:
> 
>     1. Why do we need to switch to CUDA 11.x?
> 
This is not switching to CUDA 11.x, it is simply making it possible to build and run with CUDA 11, it still works with CUDA 10, and we can keep CUDA 10 as the default and supported version for now.

I do think we might need to switch at some point, but I think we should simply follow what DPC++ is using, which I believe is still 10.2 right now but might change soon.

>     2. Has this change (CUDA version change) propagated to README? I did not see it in [Add build instruction for CUDA backends #126](https://github.com/oneapi-src/oneMKL/pull/126)
> 

As I said earlier this isn't really a version change and 10.2 should still be the default supported version so I didn't change that in the README.

>     3. Did you attach the log? I could not find it.
> 
Apologies, I didn't attach them, here's two cuBLAS ctest log files, one with CUDA 11.4 and one with CUDA 10.2:

* [cublas-cuda-10.log](https://github.com/oneapi-src/oneMKL/files/7128642/cublas-cuda-10.log)
* [cublas-cuda-11.log](https://github.com/oneapi-src/oneMKL/files/7128646/cublas-cuda-11.log)

>     4. @mkrainiuk, @jasukhar If we are changing the supported CUDA version, I think, we need to update our CI system as well.

This shouldn't be needed yet, but it might be good to start thinking about it if we want to be able to update at the same time as DPC++.

**Comment by mmeterel** [comment]
> > @npmiller Thanks for the PR. A few questions for clarity:
> > ```
> > 1. Why do we need to switch to CUDA 11.x?
> > ```
> 
> This is not switching to CUDA 11.x, it is simply making it possible to build and run with CUDA 11, it still works with CUDA 10, and we can keep CUDA 10 as the default and supported version for now.
> 
> I do think we might need to switch at some point, but I think we should simply follow what DPC++ is using, which I believe is still 10.2 right now but might change soon.

Thanks for your replies and clarification. I guess my question is, if we are not changing CUDA version, why are we trying to make oneMKL interfaces compatible with 11.x? I am not objecting the changes, just trying to understand what is driving this PR. :)


> 
> > ```
> > 2. Has this change (CUDA version change) propagated to README? I did not see it in [Add build instruction for CUDA backends #126](https://github.com/oneapi-src/oneMKL/pull/126)
> > ```
> 
> As I said earlier this isn't really a version change and 10.2 should still be the default supported version so I didn't change that in the README.

> > ```
> > 3. Did you attach the log? I could not find it.
> > ```
> 
> Apologies, I didn't attach them, here's two cuBLAS ctest log files, one with CUDA 11.4 and one with CUDA 10.2:
> 
> * [cublas-cuda-10.log](https://github.com/oneapi-src/oneMKL/files/7128642/cublas-cuda-10.log)
> * [cublas-cuda-11.log](https://github.com/oneapi-src/oneMKL/files/7128646/cublas-cuda-11.log)
> 
> > ```
> > 4. @mkrainiuk, @jasukhar If we are changing the supported CUDA version, I think, we need to update our CI system as well.
> > ```
> 
> This shouldn't be needed yet, but it might be good to start thinking about it if we want to be able to update at the same time as DPC++.

**Comment by npmiller** [comment]
> Thanks for your replies and clarification. I guess my question is, if we are not changing CUDA version, why are we trying to make oneMKL interfaces compatible with 11.x? I am not objecting the changes, just trying to understand what is driving this PR. :)

Well, I originally tried to build oneMKL with CUDA 11.4 as that's the default version on my system, and when I ran into this issue I had a quick look and it seemed small enough that it might be worth just fixing, especially since the fix would easily just work for both CUDA 10 and CUDA 11.

If it had been more involved to get it to work on CUDA 11 then it probably wouldn't be worth doing until we actually switch, but as it stands this small patch makes oneMKL usable on CUDA 11 even if we don't support it officially, and will make the transition to the new version easier if and when we decide to do it.

**Review by mmeterel — APPROVED** [review]

**Comment by mmeterel** [comment]
> > Thanks for your replies and clarification. I guess my question is, if we are not changing CUDA version, why are we trying to make oneMKL interfaces compatible with 11.x? I am not objecting the changes, just trying to understand what is driving this PR. :)
> 
> Well, I originally tried to build oneMKL with CUDA 11.4 as that's the default version on my system, and when I ran into this issue I had a quick look and it seemed small enough that it might be worth just fixing, especially since the fix would easily just work for both CUDA 10 and CUDA 11.
> 
> If it had been more involved to get it to work on CUDA 11 then it probably wouldn't be worth doing until we actually switch, but as it stands this small patch makes oneMKL usable on CUDA 11 even if we don't support it officially, and will make the transition to the new version easier if and when we decide to do it.

Agreed on your argument. Thanks for your work on the PR!

**Review by akabalov — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
