### PR TITLE
Add remaining matrix copy and transposition routines

### PR DESCRIPTION
**Pull request by andrewtbarker**
# Description

Some matrix copy and transposition routines were added in #227. This PR adds the remaining routines from the spec, including non-batch and group-batch interfaces.

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Log: [test.txt](https://github.com/oneapi-src/oneMKL/files/9922084/test.txt)
- [x] Have you formatted the code using clang-format?

## New interfaces

- [x] Have you provided motivation for adding a new feature as part of RFC and
it was accepted? [spec #420](https://github.com/oneapi-src/oneAPI-spec/pull/420)
- [x] What version of oneAPI spec the interface is targeted? (1.2 provisional rev1)

## New features

- [x] Have you provided motivation for adding a new feature?
- [x] Have you added relevant tests? (all new interfaces have unit tests)

### CODE REVIEW

**Review by b-shi — APPROVED** [review]
Changes look good to me!

**Comment by andrewtbarker** [comment]
@mkrainiuk @vmalia Can we get a couple reviews for this when you get a chance? BLAS team has reviewed and approved.

**Comment by andrewtbarker** [comment]
@dnhsieh-intel Can someone look at this please? We have approval from BLAS.

**Review by mkrainiuk — APPROVED** [review]
Looks good to me, thank you!

**Comment by mkrainiuk** [comment]
I have one quick question: did you test it with other GPUs and backends except Intel GPU with Intel oneMKL?

**Comment by andrewtbarker** [comment]
> I have one quick question: did you test it with other GPUs and backends except Intel GPU with Intel oneMKL?

No, since these are MKL-specific extensions it should throw a not implemented exception for other backends. Should I test that such exceptions are thrown as expected?

**Comment by andrewtbarker** [comment]
Can I get another approval since Brian's approval wasn't "official"? I don't think a thorough review is required since Brian actually reviewed, I just need the button to turn green...

**Comment by mkrainiuk** [comment]
> > I have one quick question: did you test it with other GPUs and backends except Intel GPU with Intel oneMKL?
> 
> No, since these are MKL-specific extensions it should throw a not implemented exception for other backends. Should I test that such exceptions are thrown as expected?

I see, in this case I think it's fine, since the unimplemented exception is the same as in the existing tests.

**Review by akabalov — APPROVED** [review]

**Pull request merged**
