### PR TITLE
[cublas] improve cuBLAS scope handle constructor

### PR DESCRIPTION
**Pull request by mkrainiuk**
# Description

This PR has a patch from @mehdi-goli for cuBLAS scope handle creation improvement.
Partially improves problems observed in #106 

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Attach a log.
```
          Start    1: BLAS/RT/Nrm2TestSuite/Nrm2Tests.RealSinglePrecision/Column_Major_TITAN_RTX
1/1324 Test    #1: BLAS/RT/Nrm2TestSuite/Nrm2Tests.RealSinglePrecision/Column_Major_TITAN_RTX ..................................   Passed    1.12 sec
          Start    2: BLAS/RT/Nrm2TestSuite/Nrm2Tests.RealSinglePrecision/Row_Major_TITAN_RTX
2/1324 Test    #2: BLAS/RT/Nrm2TestSuite/Nrm2Tests.RealSinglePrecision/Row_Major_TITAN_RTX .....................................   Passed    0.13 sec
          Start    3: BLAS/RT/Nrm2TestSuite/Nrm2Tests.RealDoublePrecision/Column_Major_TITAN_RTX
...
1323/1324 Test #1323: BLAS/CT/GemmtUsmTestSuite/GemmtUsmTests.ComplexDoublePrecision/Column_Major_TITAN_RTX .......................   Passed    0.13 sec
          Start 1324: BLAS/CT/GemmtUsmTestSuite/GemmtUsmTests.ComplexDoublePrecision/Row_Major_TITAN_RTX
1324/1324 Test #1324: BLAS/CT/GemmtUsmTestSuite/GemmtUsmTests.ComplexDoublePrecision/Row_Major_TITAN_RTX ..........................   Passed    0.14 sec

100% tests passed, 0 tests failed out of 1324
```

- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by mehdi-goli** [comment]
Thanks @mkrainiuk

**Review by mmeterel — COMMENTED** [review]
@mehdi-goli, @mkrainiuk  Thanks for the PR. Is there any reason why you want to keep the original code? Assuming the new code is more performant, I would suggest removing the old one to avoid confusion.

**Review by mmeterel — APPROVED** [review]

**Comment by mkrainiuk** [comment]
> @mehdi-goli, @mkrainiuk Thanks for the PR. Is there any reason why you want to keep the original code? Assuming the new code is more performant, I would suggest removing the old one to avoid confusion.

I don't think so, I've removed it and re-tested.

**Comment by mehdi-goli** [comment]
> > @mehdi-goli, @mkrainiuk Thanks for the PR. Is there any reason why you want to keep the original code? Assuming the new code is more performant, I would suggest removing the old one to avoid confusion.
> 
> I don't think so, I've removed it and re-tested.

Yes, there is no need to keep the commented code. Thanks @mkrainiuk

**Review by mehdi-goli — APPROVED** [review]

**Pull request merged**
