### PR TITLE
Update deprecated functionality for SYCL 2020 specification

### LINKED ISSUE #110: Update sycl:: functionality deprecated for 2020 specification
# Summary

Align all sycl:: apis with sycl 2020 spec version

# Problem statement
llvm compiler have already added new APIs and deprecated old ones (Example: get_count() for sycl::buffer), but dpcpp compiler doesn't support new versions yet.

# Preferred solution
- Update functionality marked as deprecated in sycl 2020 to the new versions
- Remove SYCL2020_DISABLE_DEPRECATION_WARNINGS macro

### PR DESCRIPTION
**Pull request by dnhsieh-intel**
# Description

This PR updates deprecated functionality for SYCL 2020 specification except cuBLAS and cuSOLVER backends. Errors occur in cuBLAS and cuSOLVER backends with the update and will be documented in a separate issue.

Partially fixes #110 

# Unit Tests
- [unitTests_dpcpp_blas.txt](https://github.com/oneapi-src/oneMKL/files/8091153/unitTests_dpcpp_blas.txt): 100% tests passed, 0 tests failed out of 3336
- [unitTests_dpcpp_lapack.txt](https://github.com/oneapi-src/oneMKL/files/8091160/unitTests_dpcpp_lapack.txt): 99% tests passed, 1 tests failed out of 1592
- [unitTests_dpcpp_rng.txt](https://github.com/oneapi-src/oneMKL/files/8091168/unitTests_dpcpp_rng.txt): 100% tests passed, 0 tests failed out of 168
- [unitTests_llvm_cublas.txt](https://github.com/oneapi-src/oneMKL/files/8091184/unitTests_llvm_cublas.txt): 100% tests passed, 0 tests failed out of 1668
- [unitTests_llvm_curand.txt](https://github.com/oneapi-src/oneMKL/files/8091187/unitTests_llvm_curand.txt): 100% tests passed, 0 tests failed out of 84

### CODE REVIEW

**Comment by dnhsieh-intel** [comment]
@sbalint98 Could you test if these changes work with hipSYCL please? It should be fine since hipSYCL is SYCL2020 compliant, but just in case.

**Comment by sbalint98** [comment]
Thank you for keeping this in mind! I'll have a look later today

**Comment by dnhsieh-intel** [comment]
Hi @sbalint98 , would it be possible for hipSYCL team to test this by the end of this week? Thank you!

**Comment by dnhsieh-intel** [comment]
Hi @sbalint98 , I advance this PR for review. Please let me know if any changes are needed from hipSYCL side.

**Comment by sbalint98** [comment]
Hi @dnhsieh-intel , I opened a PR against your branch a few days ago (https://github.com/dnhsieh-intel/oneMKL/pull/1) I am not sure if those cahnges are added or not. Can you have a look? Thank you, and sorry for the long delay.

**Comment by dnhsieh-intel** [comment]
Thank you, @sbalint98 ! I am sorry that I didn't notice your PR to my branch. The changes for hipSYCL are now added.

**Review by mmeterel — APPROVED** [review]

**Comment by dnhsieh-intel** [comment]
Resolve conflicts.

**Review by mkrainiuk — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
