### PR TITLE
[LAPACK] unit tests update

### PR DESCRIPTION
**Pull request by ericlars**
# Description
* Logging refactor
* Accuracy tests corrected and moved to common header
* Dependency variable scope fixed
* Backward compatibility with older netlib libraries with weirdNEC macro

# Checklist

## All Submissions

- [X] Do all unit tests pass locally? Attach a log.
logs to be added
- [X] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by ericlars** [comment]
Logs attached:

[log_dpcpp_lapack_cpu.txt](https://github.com/oneapi-src/oneMKL/files/8721596/log_dpcpp_lapack_cpu.txt)
[log_dpcpp_lapack_gpu.txt](https://github.com/oneapi-src/oneMKL/files/8721597/log_dpcpp_lapack_gpu.txt)
[log_llvm_lapack.txt](https://github.com/oneapi-src/oneMKL/files/8721598/log_llvm_lapack.txt)

**Review by jadurazo — APPROVED** [review]

**Comment by mmeterel** [comment]
@ericlars Have you tested for cuSOLVER backend?

**Comment by ericlars** [comment]
> @ericlars Have you tested for cuSOLVER backend?

@mmeterel I ran the test suite and it came back green.
[log_llvm_cusolver_.txt](https://github.com/oneapi-src/oneMKL/files/8788147/log_llvm_cusolver_.txt)

**Review by mmeterel — APPROVED** [review]
@ericlars Thanks for the PR. All tests passes in my local tests as well.

**Pull request merged**
