### PR TITLE
[cusolver] Add support for computation_error exceptions

### PR DESCRIPTION
**Pull request by pgorlani**
# Description

This patch applies https://github.com/oneapi-src/oneMKL/pull/162 (exception message fix) to cusolver functions.

Moreover, it introduces a check for all cusolver functions(*) that can produce computation errors (i.e., parameter ``devInfo`` can return positive values, e.g., [cusolverDn*sygvd](https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverDN-lt-t-gt-sygvd)). If the check fails a `oneapi::mkl::lapack::computation_error` exception is thrown, i.e.,
```
oneMKL: LAPACK/sygvd: computation error: cusolverDnDsygvd failed with info = 28
```
_
(*) `getrf`, `heevd`, `hetrd`, `potrf`, `potri`, `syevd`, `sygvd`, `sytrf`, and `gesvd`.

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Attach a log. --> [ctest-j32-cusolver-exc.txt](https://github.com/oneapi-src/oneMKL/files/8331645/ctest-j32-cusolver-exc.txt)
- [ ] Have you formatted the code using clang-format?

## New interfaces

- [ ] Have you provided motivation for adding a new feature as part of RFC and
it was accepted? # (RFC)
- [ ] What version of oneAPI spec the interface is targeted?
- [ ] Complete [New features](pull_request_template.md#new-features) checklist

## New features

- [ ] Have you provided motivation for adding a new feature?
- [ ] Have you added relevant tests?

## Bug fixes

- [ ] Have you added relevant regression tests?
- [ ] Have you included information on how to reproduce the issue (either in a
      GitHub issue or in this PR)?

### CODE REVIEW

**Comment by numEricL** [comment]
Thank you for this PR! I see there weren't many functions before that handled the info variable. Is there reason why you enabled the subset that you did? It looks to me that all functions could use a similar treatment.

**Comment by ericlars** [comment]
Thank you for this PR! I see there weren't many functions before that handled the info variable. Is there reason why you enabled the subset that you did? It looks to me that all functions could use a similar treatment.

**Comment by pgorlani** [comment]
You are welcome!

The functions in this subset are the only ones that can return `devInfo > 0`  for signaling a computational error, which will be silent otherwise. All the other functions return only `devInfo < 0` for signaling a wrong parameter, but in this case the error is already signaled by throwing a  `CUSOLVER_STATUS_INVALID_VALUE` exception.

**Review by ericlars — APPROVED** [review]

**Comment by ericlars** [comment]
I see, that's reasonable.

**Comment by mmeterel** [comment]
@ericlars could you run and verify CI please?

**Comment by ericlars** [comment]
> @ericlars could you run and verify CI please?

@mmeterel The cuSOLVER backend hasn't been integrated into CI yet (waiting on PR #184). I ran unit testing locally and my results matches the submitted results.

**Review by sknepper — APPROVED** [review]
This looks great to me! Thanks much!!

**Pull request merged**
