### PR TITLE
[docs] [BLAS] make documentation consistent with oneAPI spec

### PR DESCRIPTION
**Pull request by andrewtbarker**
# Description

Update documentation of BLAS interfaces to be consistent with the [oneAPI spec](https://github.com/oneapi-src/oneAPI-spec).

# Checklist

All changes are to `.rst` files. No code changes, no new interface, no new feature, no bug fixes.

Log from `make Documentation`:
```
Scanning dependencies of target Documentation
Building HTML documentation with Sphinx
Built target Documentation
```

### CODE REVIEW

**Comment by mmeterel** [comment]
@andrewtbarker Did you check the existing ones, if they match to oneAPI spec exactly or not?

**Comment by andrewtbarker** [comment]
Yes, `gemm`, `gemv` and a few others had changes in spec that I ported into this PR. It's possible I missed some but I used a script to compare so I think I got them all.

**Comment by mmeterel** [comment]
> Yes, `gemm`, `gemv` and a few others had changes in spec that I ported into this PR. It's possible I missed some but I used a script to compare so I think I got them all.

Thanks for checking. Were you able to build the documentation?

**Comment by mmeterel** [comment]
@andrewtbarker Looks like we don't have gemm_batch span api supported in this repo yet. Could you please remove that from the documentation? gemm_batch span api needs to be added to this repo before we add the documentation for it.

**Comment by andrewtbarker** [comment]
Removed the span API. The docs build successfully with no warnings/errors, the .html files are there but I haven't tried to look at them in a browser.

**Review by mmeterel — APPROVED** [review]
@andrewtbarker  Thanks for the PR. Looks good to me.

**Comment by mmeterel** [comment]
@trosenqu Can you please help with re-building the documentation once this PR is merged?

**Review by mkrainiuk — APPROVED** [review]
Looks good to me, thank you!

**Comment by trosenqu** [comment]
> @trosenqu Can you please help with re-building the documentation once this PR is merged?

@mmeterel: Yes, Ben and I will re-build. Thx.

**Comment by trosenqu** [comment]
> > @trosenqu Can you please help with re-building the documentation once this PR is merged?
> 
> @mmeterel: Yes, Ben and I will re-build. Thx.

Done. @fitchbe and I have submitted a pull request.

**Pull request merged**
