### PR TITLE
[SYCL-BLAS] fix SYCL-BLAS backend names in backend table

### PR DESCRIPTION
**Pull request by andrewtbarker**
# Description

Fixes config/build for SYCL-BLAS to use correct `#define` names in backend table

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Log: [out.txt](https://github.com/oneapi-src/oneMKL/files/12029380/out.txt)
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Review by toxicscum — APPROVED** [review]

**Comment by mmeterel** [comment]
What was error signature before this PR?

**Comment by andrewtbarker** [comment]
@asrednit said he saw the following:
```
1: [ RUN      ] Nrm2TestSuite/Nrm2Tests.RealSinglePrecision/Column_Major_Intel_R__Xeon_R__Platinum_8358_CPU___2_60GHz
1: unknown file: Failure
1: C++ exception with description "oneMKL: Couldn't load selected backend" thrown in the test body.
```
It is a bit strange because I am not sure how this could have ever configured/built properly before but I remember doing it. Maybe @hjabird or @pgorlani have insights - there might be a configuration step we are missing instead of the change to the header file.

**Comment by mmeterel** [comment]
> @asrednit said he saw the following:
> 
> ```
> 1: [ RUN      ] Nrm2TestSuite/Nrm2Tests.RealSinglePrecision/Column_Major_Intel_R__Xeon_R__Platinum_8358_CPU___2_60GHz
> 1: unknown file: Failure
> 1: C++ exception with description "oneMKL: Couldn't load selected backend" thrown in the test body.
> ```
> 
> It is a bit strange because I am not sure how this could have ever configured/built properly before but I remember doing it. Maybe @hjabird or @pgorlani have insights - there might be a configuration step we are missing instead of the change to the header file.

Yes, that is exactly my concern. The PR looks good, but it would good to understand how this was missed.

**Review by mmeterel — APPROVED** [review]

**Review by Rbiessy — APPROVED** [review]
Thank you for this fix. The macro name changed during the review, I don't know how it still worked for us.

**Pull request merged**
